# Python Lesson 55: Counting: Permutations and Combinations

**Concept page:** `wiki/concepts/counting-permutations-and-combinations.md` · **Area:** probability

**You will be able to:**
- apply the sum and product rules
- compute P(n,r) and C(n,r)
- verify Pascal's triangle and the binomial theorem
- connect counting to probability

*How to use:* run the cells top to bottom, read the output, then try the **Exercises** in the empty cells before opening the **Solutions** section at the bottom.

In [1]:
import numpy as np
import sympy as sp
import matplotlib
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)
%matplotlib inline

## 1. Product and sum rules

In [2]:
import itertools, math
print(4*3)                                   # 4 shirts x 3 shorts
dice=list(itertools.product(range(1,7),repeat=2))
A={d for d in dice if sum(d)==4}; B={d for d in dice if d[0]*d[1]==4}
print(len(A),len(B),len(A|B),len(A)+len(B)-len(A&B))   # 3 3 5 5

12
3 3 5 5


## 2. Permutations and combinations

In [3]:
P=lambda n,r: math.factorial(n)//math.factorial(n-r)
C=lambda n,r: P(n,r)//math.factorial(r)
print(P(6,4),P(7,3),C(4,2))
assert P(6,4)==len(list(itertools.permutations(range(6),4)))
assert C(4,2)==len(list(itertools.combinations(range(4),2)))
assert C(10,3)==math.comb(10,3)

360 210 6


## 3. Pascal's triangle and the binomial theorem

In [4]:
rows=[[math.comb(n,r) for r in range(n+1)] for n in range(7)]
for r in rows: print(r)
assert all(rows[n][r]==rows[n-1][r-1]+rows[n-1][r] for n in range(2,7) for r in range(1,n))
a=sp.symbols('a'); print(sp.expand((1+a)**4))
assert all(sum(row)==2**n for n,row in enumerate(rows))

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]
[1, 6, 15, 20, 15, 6, 1]
a**4 + 4*a**3 + 6*a**2 + 4*a + 1


## 4. Counting → probability

In [5]:
n=23
p_no=np.prod([(365-k)/365 for k in range(n)]); print(1-p_no)       # 0.507
print(P(365,n)/365**n==p_no or abs(P(365,n)/365**n-p_no)<1e-12)
print(math.comb(10,3)*0.5**10)    # P(exactly 3 heads in 10 fair tosses)

0.5072972343239857
True
0.1171875


## 5. Circular arrangements

In [6]:
def circ(n): return math.factorial(n-1)
print(circ(6),2*circ(5))   # 120 and the 2 adjacent women: 48 = 2! * 4!
seats=set()
for perm in itertools.permutations(range(5)):
    k=perm.index(0); seats.add(perm[k:]+perm[:k])
print(len(seats),circ(5))

120 48
24 24


## Cambodian textbook corner (កម្មវិធីសិក្សាកម្ពុជា)
Grade 10 vol. 2 ch. 8 (pp. 62-83): $P(6,4)=360$, $P(7,3)=210$, circular $(n-1)!$, $C(4,2)=6$, Pascal's triangle and $(1+a)^n$.

In [7]:
print(P(6,4),P(7,3),circ(6),C(4,2),sp.expand((1+a)**4))

360 210 120 6 a**4 + 4*a**3 + 6*a**2 + 4*a + 1


**Textbook example (G10 v2 p. 85):** if $(a-\tfrac12x)^6=b-96x+cx^2+\dots$ find $a,b,c$ by matching binomial coefficients.

In [8]:
a,x=sp.symbols('a x'); co=sp.Poly(sp.expand((a-x/2)**6),x).all_coeffs()[::-1]
sol=[s for s in sp.solve(sp.Eq(co[1],-96),a) if s.is_real][0]
print(sol,co[0].subs(a,sol),co[2].subs(a,sol)); assert (sol,co[0].subs(a,sol),co[2].subs(a,sol))==(2,64,60)

2 64 60


## Exercises

**Exercise 1.** How many 4-digit codes use distinct digits from 1-6? How many 3-letter 'words' from 7 distinct letters? Check both by enumeration.

In [9]:
# your code here

**Exercise 2.** A committee of 4 (president, vice, secretary, member) is chosen from 10 students; then a committee of 4 with no roles. Compute both and their ratio.

In [10]:
# your code here

**Exercise 3.** Show that C(n,0)+...+C(n,n)=2^n for n=0..10 (number of subsets).

In [11]:
# your code here

## Solutions
*(Try the exercises first!)*

In [12]:
# Solution 1
print(P(6,4),P(7,3)); assert P(6,4)==len(list(itertools.permutations(range(1,7),4))); assert P(7,3)==210

360 210


In [13]:
# Solution 2
print(P(10,4),C(10,4),P(10,4)/C(10,4)); assert P(10,4)//C(10,4)==24

5040 210 24.0


In [14]:
# Solution 3
assert all(sum(math.comb(n,r) for r in range(n+1))==2**n for n in range(11)); print('ok')

ok
